In [4]:
#Using negative index 
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr[-1,-1])
print(arr[-2,-1])

8
4


In [9]:
#Array Slicing
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[0:5])
print(arr[3:])
print(arr[:6])
print(arr[-5:-1])
print(arr[0:10:2])

[1 2 3 4 5]
[4 5 6 7 8 9]
[1 2 3 4 5 6]
[5 6 7 8]
[1 3 5 7 9]


In [18]:
#2-D Array Slicing
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,0:4])
print(arr[1,0:4])
print(arr[0:2,2])
print(arr[0:2,0:4])

[1 2 3 4]
[6 7 8 9]
[3 8]
[[1 2 3 4]
 [6 7 8 9]]


In [20]:
#Methods
# Copy -copy method not changes original array
# view - view method cchanges original array
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
x = arr1.copy()
y = arr2.view()
arr1[0] = 11
arr2[0]  = 12
print(arr1)
print(x)
print(arr2)
print(y)

[11  2  3  4  5]
[1 2 3 4 5]
[12  7  8  9 10]
[12  7  8  9 10]


In [21]:
#Concatenate()- Joining arrays
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr = np.concatenate((arr1,arr2))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [24]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[6,7,8],[8,9,10]])
arr = np.concatenate((arr1,arr2), axis = 1)
print(arr)

[[ 1  2  3  6  7  8]
 [ 4  5  6  8  9 10]]


In [29]:
#array_split
import numpy as np
arr1 = np.array([1,2,3,4,5,6,7,8])
arr = np.array_split(arr1,3)
arr2 = np.array_split(arr1,4)
print(arr)
print(arr2)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]
