1.How to extract items that satisfy a given condition from 1D array?
Q. Extract all odd numbers from arr

Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2.How to replace items that satisfy a condition with another value in numpy array?

In [ ]:
Q. Replace all odd numbers in arr with -1

Input:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3.How to replace items that satisfy a condition without affecting the original array?

In [ ]:
Q. Replace all odd numbers in arr with -1 without changing arr

Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

4.How to reshape an array?

In [ ]:
Q. Convert a 1D array to a 2D array with 2 rows

Input:

np.arange(10)

#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

5.How to stack two arrays vertically?

In [ ]:
Q. Stack arrays a and b vertically

Input

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

6.How to stack two arrays horizontally?

In [ ]:
Q. Stack the arrays a and b horizontally.

Input

a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

7.How to generate custom sequences in numpy without hardcoding?

In [ ]:
Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:
a = np.array([1,2,3])`

8.How to get the common items between two python numpy arrays?

In [ ]:
Q. Get the common items between a and b

Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

9.How to remove from one array those items that exist in another?

In [ ]:
Q. From array a remove all items present in array b

Input:

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

10.How to get the positions where elements of two arrays match?

In [ ]:
Q. Get the positions where elements of a and b match

Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

11.How to extract all numbers between a given range from a numpy array?

In [ ]:
Q. Get all items between 5 and 10 from a.

Input:

a = np.array([2, 6, 1, 9, 10, 3, 27])

12.How to make a python function that handles scalars to work on numpy arrays?

In [ ]:
Q. Convert the function maxx that works on two scalars, to work on two arrays.

Input:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
#> 5

13.How to swap two columns in a 2d numpy array?

In [ ]:
Q. Swap columns 1 and 2 in the array arr.

arr = np.arange(9).reshape(3,3)
arr

14.How to swap two rows in a 2d numpy array?

In [ ]:
Q. Swap rows 1 and 2 in the array arr:

arr = np.arange(9).reshape(3,3)
arr

15.How to reverse the rows of a 2D array?

In [ ]:
Q. Reverse the rows of a 2D array arr.

# Input
arr = np.arange(9).reshape(3,3)

16.How to reverse the columns of a 2D array?

In [ ]:
Q. Reverse the columns of a 2D array arr.

# Input
arr = np.arange(9).reshape(3,3)

17.How to create a 2D array containing random floats between 5 and 10?

In [ ]:
Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

18.How to print only 3 decimal places in python numpy array?

In [ ]:
Q. Print or show only 3 decimal places of the numpy array rand_arr.

Input:

rand_arr = np.random.random((5,3))

19.How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

In [ ]:
Q. Pretty print rand_arr by suppressing the scientific notation (like 1e10)

Input:

# Create the random array
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

#> array([[  5.434049e-04,   2.783694e-04,   4.245176e-04],
#>        [  8.447761e-04,   4.718856e-06,   1.215691e-04],
#>        [  6.707491e-04,   8.258528e-04,   1.367066e-04]])

20.How to limit the number of items printed in output of numpy array?

In [ ]:
Q. Limit the number of items printed in python numpy array a to a maximum of 6 elements.
Input:

a = np.arange(15)
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])